// client/src/pages/TeletherapyRoom.jsx
import React, { useState, useEffect } from 'react'
import { useParams, useNavigate } from 'react-router-dom'
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query'
import { Button } from '@/components/ui/button'
import { Badge } from '@/components/ui/badge'
import { Mic, MicOff, Video, VideoOff, Circle, PhoneOff, Lock, MessageCircle } from 'lucide-react'
import { api } from '../services/api'
import { toast } from 'react-hot-toast'
import LoadingScreen from '../components/LoadingScreen'
import ChatWindow from '../components/ChatWindow'

const TeletherapyRoom = () => {
  const { sessionId } = useParams()
  const navigate = useNavigate()
  const queryClient = useQueryClient()

  // Fetch session details to get the actual meetingUrl generated by the backend
  const { data: session, isLoading: isSessionLoading } = useQuery({
    queryKey: ['session', sessionId],
    queryFn: () => api.sessions.getById(sessionId),
    enabled: !!sessionId
  })

  // Fetch all patients (as fallback caseload context)
  const { data: patients = [], isLoading: isPatientsLoading } = useQuery({
    queryKey: ['patients'],
    queryFn: () => api.patients.getAll().then(res => res)
  })

  const selectedPatient = session?.patient || patients[0]

  const [sessionTime, setSessionTime] = useState(0)
  const [isMuted, setIsMuted] = useState(false)
  const [isVideoOff, setIsVideoOff] = useState(false)
  const [isRecording, setIsRecording] = useState(false)
  const [isChatOpen, setIsChatOpen] = useState(false)
  
  // Use the meeting URL generated by the backend, fallback to VDO.Ninja
  const jitsiRoomUrl = session?.meetingUrl || `https://vdo.ninja/?room=speechsync-${sessionId}`;

  useEffect(() => {
    const timer = setInterval(() => setSessionTime(t => t + 1), 1000)
    return () => clearInterval(timer)
  }, [])

  // End session mutation
  const endSessionMutation = useMutation({
    mutationFn: () => api.teletherapy.endSession(sessionId, sessionTime),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['patient'] });
      queryClient.invalidateQueries({ queryKey: ['patient-history'] });
      queryClient.invalidateQueries({ queryKey: ['patient-sessions'] });
      queryClient.invalidateQueries({ queryKey: ['sessions'] });
      
      toast.success('Session completed! Navigating to AI Clinical Assistant.');
      navigate(`/ai-session-form?patientId=${selectedPatient?.id}`);
    },
    onError: (err) => {
      toast.error(`Failed to end session: ${err.message}`);
    }
  });

  const handleEndSession = () => {
    endSessionMutation.mutate();
  };

  if (isSessionLoading || isPatientsLoading) return <LoadingScreen />

  if (!selectedPatient) {
    return (
      <div className="p-8 text-center text-slate-500 italic max-w-xl mx-auto mt-20 bg-white border border-slate-200 rounded-2xl p-12">
        <h3 className="font-bold text-lg text-slate-800">No Patient Associated</h3>
        <p className="text-slate-400 text-sm mt-1">This appointment is not linked to any patient.</p>
        <Button className="mt-4" onClick={() => navigate('/dashboard')}>Back to Dashboard</Button>
      </div>
    )
  }

  const formatTime = (secs) => {
    const m = Math.floor(secs / 60).toString().padStart(2, '0')
    const s = (secs % 60).toString().padStart(2, '0')
    return `${m}:${s}`
  }

  const isEndingSession = endSessionMutation.isPending

  return (
    <div className="flex h-[calc(100vh-theme(spacing.20))] bg-slate-900 overflow-hidden relative">
      {/* Full Width Video Area */}
      <div className="w-full h-full flex flex-col relative">

        {/* Top Bar */}
        <div className="h-12 bg-slate-950/80 backdrop-blur border-b border-slate-800 flex items-center justify-between px-6 absolute top-0 w-full z-20">
          <div className="flex items-center gap-2 text-slate-400 text-xs font-semibold">
            <Lock className="h-3.5 w-3.5 text-emerald-500" />
            <span>🔒 SECURE TELEHEALTH CONNECTION</span>
          </div>
          <div className="font-mono font-bold text-white bg-slate-800 px-3 py-1 rounded-md border border-slate-700 tracking-wider">
            {formatTime(sessionTime)}
          </div>
          <div className="flex items-center gap-4">
            <Button 
              variant="outline" 
              size="sm" 
              onClick={() => setIsChatOpen(true)}
              className="bg-primary/20 hover:bg-primary/30 border-primary/50 text-white flex items-center gap-2 rounded-full h-8 px-3"
            >
              <MessageCircle className="h-4 w-4" /> Message Parent
            </Button>
            <Badge variant="outline" className="bg-red-500/10 border-red-500/30 text-red-400 font-semibold px-2 py-0.5 animate-pulse text-[10px]">
              LIVE TELEHEALTH
            </Badge>
          </div>
        </div>

        {/* Jitsi Video Call Integration */}
        <div className="flex-1 bg-slate-950 relative flex items-center justify-center pt-12">
          <div className="w-full h-full p-4 pb-16">
            <iframe
              src={jitsiRoomUrl}
              allow="camera; microphone; fullscreen; speaker; display-capture"
              className="w-full h-full border border-slate-850 rounded-2xl bg-slate-950 shadow-2xl animate-in zoom-in-95 duration-300"
              title="Secure Teletherapy Session"
            />
          </div>

          {/* SLP Video (PiP) */}
          <div className="absolute bottom-24 right-6 w-48 h-32 bg-slate-900 rounded-xl border-2 border-slate-700 shadow-2xl overflow-hidden z-20">
            <img
              src="https://placehold.co/320x240/0f172a/94a3b8?text=Your+Camera"
              alt="SLP Video"
              className="w-full h-full object-cover"
            />
          </div>
        </div>

        {/* Control Bar */}
        <div className="h-20 bg-slate-950 border-t border-slate-800 flex items-center justify-center gap-4 px-6 z-20">
          <Button
            variant="outline"
            size="icon"
            onClick={() => setIsMuted(!isMuted)}
            className={`h-12 w-12 rounded-full border-slate-700 bg-slate-900 text-slate-300 hover:bg-slate-800 ${isMuted ? 'bg-red-500/20 border-red-500 text-red-500 hover:bg-red-500/30' : ''}`}
          >
            {isMuted ? <MicOff className="h-5 w-5" /> : <Mic className="h-5 w-5" />}
          </Button>
          <Button
            variant="outline"
            size="icon"
            onClick={() => setIsVideoOff(!isVideoOff)}
            className={`h-12 w-12 rounded-full border-slate-700 bg-slate-900 text-slate-300 hover:bg-slate-800 ${isVideoOff ? 'bg-red-500/20 border-red-500 text-red-500 hover:bg-red-500/30' : ''}`}
          >
            {isVideoOff ? <VideoOff className="h-5 w-5" /> : <Video className="h-5 w-5" />}
          </Button>
          <Button
            variant="outline"
            size="icon"
            onClick={() => setIsRecording(!isRecording)}
            className={`h-12 w-12 rounded-full border-slate-700 bg-slate-900 text-slate-300 hover:bg-slate-800 ${isRecording ? 'border-red-500 text-red-500 animate-pulse bg-red-500/10' : ''}`}
          >
            <Circle className={`h-5 w-5 ${isRecording ? 'fill-red-500' : 'text-slate-400'}`} />
          </Button>
          <div className="w-px h-8 bg-slate-800 mx-2"></div>
          <Button
            variant="destructive"
            onClick={handleEndSession}
            disabled={isEndingSession}
            className="h-12 px-6 rounded-full font-bold shadow-lg"
          >
            <PhoneOff className="mr-2 h-5 w-5" /> End Session
          </Button>
        </div>
      </div>

      <ChatWindow 
        isOpen={isChatOpen} 
        onClose={() => setIsChatOpen(false)} 
        recipientId={selectedPatient?.parentUserId}
        patientId={selectedPatient?.id}
        title={`Message Parent (${selectedPatient?.name})`}
      />
    </div>
  )
}

export default TeletherapyRoom