import { Router } from 'express';
import { PrismaClient } from '@prisma/client';
import authenticate from '../middleware/authenticate.js';
import { authorize } from '../middleware/authorize.js';
import PDFDocument from 'pdfkit';



const router = Router();
const prisma = new PrismaClient();

// Helper to generate a PDF report for a patient's goals
async function generatePdfReport(res, studentName, grade, disorder, iepDueDate, goals, userId, resourceId) {
  const doc = new PDFDocument({ margin: 50 });
  
  res.setHeader('Content-Type', 'application/pdf');
  res.setHeader('Content-Disposition', `attachment; filename=IEP_Report_${studentName.replace(/\s+/g, '_')}.pdf`);
  
  doc.pipe(res);

  // Header
  doc.fontSize(20).font('Helvetica-Bold').fillColor('#1E3A8A').text('SpeechSync', 50, 50);
  doc.fontSize(10).font('Helvetica').fillColor('#6B7280').text('FERPA-Compliant Progress Report', 50, 75);
  doc.moveTo(50, 95).lineTo(545, 95).stroke('#E5E7EB');

  // Student Info
  doc.fontSize(16).font('Helvetica-Bold').fillColor('#111827').text('IEP Progress Summary', 50, 115);
  doc.fontSize(11).font('Helvetica').fillColor('#374151');
  doc.text(`Student: ${studentName}`, 50, 145);
  doc.text(`Grade: ${grade || 'N/A'}`, 50, 162);
  doc.text(`Primary Disorder: ${disorder || 'N/A'}`, 50, 179);
  doc.text(`IEP Due: ${iepDueDate ? new Date(iepDueDate).toLocaleDateString('en-IN') : 'N/A'}`, 50, 196);
  doc.text(`Report Generated: ${new Date().toLocaleDateString('en-IN')}`, 50, 213);

  // Goals Section
  if (goals && goals.length) {
    doc.fontSize(14).font('Helvetica-Bold').fillColor('#1E3A8A').text('Current Goals', 50, 250);
    let y = 275;
    for (const goal of goals) {
      doc.fontSize(10).font('Helvetica-Bold').fillColor('#111827').text(goal.domain, 50, y);
      doc.font('Helvetica').fillColor('#374151').text(goal.goalText, 50, y + 15, { width: 495 });
      const pct = goal.target > 0 ? Math.round((goal.current / goal.target) * 100) : 0;
      doc.text(`Progress: ${goal.current}% of ${goal.target}% target (${pct}% of goal met) — Status: ${goal.status}`, 50, y + 40);
      
      // Progress bar background
      doc.rect(50, y + 58, 495, 8).fillColor('#E5E7EB').fill();
      // Progress bar fill
      const progressWidth = 495 * (Math.min(100, goal.current) / 100);
      if (progressWidth > 0) {
        doc.rect(50, y + 58, progressWidth, 8).fillColor(goal.status === 'MET' ? '#10B981' : '#F59E0B').fill();
      }
      
      doc.fillColor('#374151');
      y += 90;
      if (y > 700) {
        doc.addPage();
        y = 50;
      }
    }
  } else {
    doc.fontSize(11).font('Helvetica-Oblique').fillColor('#6B7280').text('No active goals recorded for this patient.', 50, 250);
  }

  // Compliance Footer
  doc.fontSize(8).fillColor('#9CA3AF').text('This document is FERPA-compliant. Generated by SpeechSync Clinical Platform. HIPAA compliant. AES-256 encrypted at rest.', 50, 750, { width: 495, align: 'center' });

  doc.end();

  // Audit Log
  await prisma.auditLog.create({
    data: {
      userId,
      action: 'EXPORT',
      resource: 'IEP_REPORT',
      resourceId,
      details: { studentName }
    }
  });
}

// GET /api/reports/iep/progress-report/:studentId (IEP student report)
router.get('/iep/progress-report/:studentId', authenticate, authorize('SCHOOL_COORDINATOR', 'ADMIN', 'SLP'), async (req, res) => {
  try {
    const student = await prisma.iepStudent.findUnique({
      where: { id: req.params.studentId }
    });

    if (!student) {
      return res.status(404).json({ error: 'IEP Student record not found' });
    }

    const patient = student.patientId ? await prisma.patient.findUnique({
      where: { id: student.patientId },
      include: { goals: true }
    }) : null;

    const goals = patient ? patient.goals : [];

    await generatePdfReport(
      res,
      student.name,
      student.grade,
      student.disorder,
      student.iepDueDate,
      goals,
      req.user.id,
      student.id
    );
  } catch (error) {
    console.error('Generate IEP PDF report error:', error);
    if (!res.headersSent) {
      res.status(500).json({ error: 'Internal server error' });
    }
  }
});

// GET /api/reports/iep/:patientId (Direct patient profile PDF export)
router.get('/iep/:patientId', authenticate, authorize('SCHOOL_COORDINATOR', 'ADMIN', 'SLP'), async (req, res) => {
  try {
    const patient = await prisma.patient.findUnique({
      where: { id: req.params.patientId },
      include: { goals: true }
    });

    if (!patient) {
      return res.status(404).json({ error: 'Patient not found' });
    }

    // Attempt to match with an iepStudent record
    const student = await prisma.iepStudent.findFirst({
      where: { patientId: patient.id }
    });

    await generatePdfReport(
      res,
      patient.name,
      student ? student.grade : 'N/A',
      patient.diagnoses.join(', '),
      student ? student.iepDueDate : null,
      patient.goals,
      req.user.id,
      patient.id
    );
  } catch (error) {
    console.error('Generate Patient PDF report error:', error);
    if (!res.headersSent) {
      res.status(500).json({ error: 'Internal server error' });
    }
  }
});

export default router;
