import { Router } from 'express';
import { PrismaClient } from '@prisma/client';
import authenticate from '../middleware/authenticate.js';
import { authorize } from '../middleware/authorize.js';
import PDFDocument from 'pdfkit';



const router = Router();
const prisma = new PrismaClient();

// Helper to generate a PDF report for a patient's goals
async function generatePdfReport(res, studentName, grade, disorder, iepDueDate, goals, userId, resourceId) {
  const doc = new PDFDocument({ margin: 50 });
  
  res.setHeader('Content-Type', 'application/pdf');
  res.setHeader('Content-Disposition', `attachment; filename=IEP_Report_${studentName.replace(/\s+/g, '_')}.pdf`);
  
  doc.pipe(res);

  // Header
  doc.fontSize(20).font('Helvetica-Bold').fillColor('#1E3A8A').text('SpeechSync', 50, 50);
  doc.fontSize(10).font('Helvetica').fillColor('#6B7280').text('FERPA-Compliant Progress Report', 50, 75);
  doc.moveTo(50, 95).lineTo(545, 95).stroke('#E5E7EB');

  // Student Info
  doc.fontSize(16).font('Helvetica-Bold').fillColor('#111827').text('IEP Progress Summary', 50, 115);
  doc.fontSize(11).font('Helvetica').fillColor('#374151');
  doc.text(`Student: ${studentName}`, 50, 145);
  doc.text(`Grade: ${grade || 'N/A'}`, 50, 162);
  doc.text(`Primary Disorder: ${disorder || 'N/A'}`, 50, 179);
  doc.text(`IEP Due: ${iepDueDate ? new Date(iepDueDate).toLocaleDateString('en-IN') : 'N/A'}`, 50, 196);
  doc.text(`Report Generated: ${new Date().toLocaleDateString('en-IN')}`, 50, 213);

  // Goals Section
  if (goals && goals.length) {
    doc.fontSize(14).font('Helvetica-Bold').fillColor('#1E3A8A').text('Current Goals', 50, 250);
    let y = 275;
    for (const goal of goals) {
      doc.fontSize(10).font('Helvetica-Bold').fillColor('#111827').text(goal.domain, 50, y);
      doc.font('Helvetica').fillColor('#374151').text(goal.goalText, 50, y + 15, { width: 495 });
      const pct = goal.target > 0 ? Math.round((goal.current / goal.target) * 100) : 0;
      doc.text(`Progress: ${goal.current}% of ${goal.target}% target (${pct}% of goal met) — Status: ${goal.status}`, 50, y + 40);
      
      // Progress bar background
      doc.rect(50, y + 58, 495, 8).fillColor('#E5E7EB').fill();
      // Progress bar fill
      const progressWidth = 495 * (Math.min(100, goal.current) / 100);
      if (progressWidth > 0) {
        doc.rect(50, y + 58, progressWidth, 8).fillColor(goal.status === 'MET' ? '#10B981' : '#F59E0B').fill();
      }
      
      doc.fillColor('#374151');
      y += 90;
      if (y > 700) {
        doc.addPage();
        y = 50;
      }
    }
  } else {
    doc.fontSize(11).font('Helvetica-Oblique').fillColor('#6B7280').text('No active goals recorded for this patient.', 50, 250);
  }

  // Compliance Footer
  doc.fontSize(8).fillColor('#9CA3AF').text('This document is FERPA-compliant. Generated by SpeechSync Clinical Platform. HIPAA compliant. AES-256 encrypted at rest.', 50, 750, { width: 495, align: 'center' });

  doc.end();

  // Audit Log
  await prisma.auditLog.create({
    data: {
      userId,
      action: 'EXPORT',
      resource: 'IEP_REPORT',
      resourceId,
      details: { studentName }
    }
  });
}

// GET /api/reports/iep/progress-report/:studentId (IEP student report)
router.get('/iep/progress-report/:studentId', authenticate, authorize('SCHOOL_COORDINATOR', 'ADMIN', 'SLP'), async (req, res) => {
  try {
    const student = await prisma.iepStudent.findUnique({
      where: { id: req.params.studentId }
    });

    if (!student) {
      return res.status(404).json({ error: 'IEP Student record not found' });
    }

    const patient = student.patientId ? await prisma.patient.findUnique({
      where: { id: student.patientId },
      include: { goals: true }
    }) : null;

    const goals = patient ? patient.goals : [];

    await generatePdfReport(
      res,
      student.name,
      student.grade,
      student.disorder,
      student.iepDueDate,
      goals,
      req.user.id,
      student.id
    );
  } catch (error) {
    console.error('Generate IEP PDF report error:', error);
    if (!res.headersSent) {
      res.status(500).json({ error: 'Internal server error' });
    }
  }
});

// GET /api/reports/iep/:patientId (Direct patient profile PDF export)
router.get('/iep/:patientId', authenticate, authorize('SCHOOL_COORDINATOR', 'ADMIN', 'SLP'), async (req, res) => {
  try {
    const patient = await prisma.patient.findUnique({
      where: { id: req.params.patientId },
      include: { goals: true }
    });

    if (!patient) {
      return res.status(404).json({ error: 'Patient not found' });
    }

    // Attempt to match with an iepStudent record
    const student = await prisma.iepStudent.findFirst({
      where: { patientId: patient.id }
    });

    await generatePdfReport(
      res,
      patient.name,
      student ? student.grade : 'N/A',
      patient.diagnoses.join(', '),
      student ? student.iepDueDate : null,
      patient.goals,
      req.user.id,
      patient.id
    );
  } catch (error) {
    console.error('Generate Patient PDF report error:', error);
    if (!res.headersSent) {
      res.status(500).json({ error: 'Internal server error' });
    }
  }
});

// GET /api/reports/:patientId/download (Comprehensive Patient Report)
router.get('/:patientId/download', authenticate, async (req, res) => {
  try {
    const { patientId } = req.params;
    
    // Fetch patient data with necessary relations
    const patient = await prisma.patient.findUnique({
      where: { id: patientId },
      include: {
        assignedSlp: true,
        sessions: {
          orderBy: { dateOfService: 'desc' },
          take: 5
        },
        goals: true,
        assessments: {
          orderBy: { dateAdministered: 'desc' },
          take: 3
        },
        invoices: {
          where: { status: { notIn: ['PAID', 'CANCELLED'] } }
        }
      }
    });

    if (!patient) {
      return res.status(404).json({ error: 'Patient not found' });
    }

    // Role-based access control
    if (req.user.role === 'PARENT') {
      const parentUserMap = await prisma.parent.findUnique({ where: { userId: req.user.id }, include: { patients: true } });
      const isParent = parentUserMap?.patients.some(p => p.patientId === patientId);
      if (!isParent) {
         return res.status(403).json({ error: 'Forbidden' });
      }
    } else if (req.user.role === 'SCHOOL_COORDINATOR') {
      const schoolUserMap = await prisma.school.findUnique({ where: { userId: req.user.id }, include: { patients: true } });
      const isSchool = schoolUserMap?.patients.some(p => p.patientId === patientId);
      if (!isSchool) {
         return res.status(403).json({ error: 'Forbidden' });
      }
    }

    // Create a PDF document
    const doc = new PDFDocument({ margin: 50 });
    
    // Set response headers to prompt a file download
    res.setHeader('Content-disposition', `attachment; filename="SpeechSync_Report_${patient.name.replace(/\\s+/g, '_')}.pdf"`);
    res.setHeader('Content-type', 'application/pdf');

    // Pipe the PDF document to the response
    doc.pipe(res);

    // Title and Header
    doc.fontSize(20).text('SpeechSync Clinical Report', { align: 'center' });
    doc.moveDown();
    
    // Patient Summary
    doc.fontSize(16).text('Patient Summary', { underline: true });
    doc.fontSize(12).text(`Name: ${patient.name}`);
    doc.text(`DOB: ${new Date(patient.dob).toLocaleDateString()}`);
    doc.text(`Diagnosis: ${patient.diagnoses.join(', ')}`);
    doc.text(`Assigned SLP: ${patient.assignedSlp?.name}`);
    doc.moveDown();

    // Goals
    doc.fontSize(16).text('Active Goals', { underline: true });
    patient.goals.forEach(goal => {
      doc.fontSize(12).text(`- [${goal.domain}] ${goal.goalText}`);
      doc.fontSize(10).text(`  Status: ${goal.status} | Target: ${goal.target}%`);
    });
    doc.moveDown();

    // Recent Sessions
    doc.fontSize(16).text('Recent Sessions', { underline: true });
    patient.sessions.forEach(session => {
      doc.fontSize(12).text(`- Date: ${new Date(session.dateOfService).toLocaleDateString()}`);
      doc.fontSize(10).text(`  Duration: ${session.durationMinutes} min | CPT: ${session.cptCode}`);
      if (session.soapNote) {
         doc.text(`  Note: ${JSON.stringify(session.soapNote)}`);
      }
      doc.moveDown(0.5);
    });
    doc.moveDown();

    // Recent Assessments
    doc.fontSize(16).text('Recent Assessments', { underline: true });
    patient.assessments.forEach(assessment => {
      doc.fontSize(12).text(`- ${assessment.testName} (${new Date(assessment.dateAdministered).toLocaleDateString()})`);
      doc.fontSize(10).text(`  Standard Score: ${assessment.standardScore || 'N/A'}`);
    });
    doc.moveDown();

    // Billing Summary (Only for Parent / Admin / SLP)
    if (req.user.role !== 'SCHOOL_COORDINATOR') {
      doc.fontSize(16).text('Billing Summary', { underline: true });
      const outstanding = patient.invoices.reduce((sum, inv) => sum + inv.balanceAmount, 0);
      doc.fontSize(12).text(`Outstanding Balance: $${outstanding.toFixed(2)}`);
    }

    // Finalize the PDF
    doc.end();

    // Log the download
    const reportRecord = await prisma.report.create({
      data: {
        patientId: patientId,
        type: 'PROGRESS',
        generatedBy: req.user.id,
        fileUrl: 'generated_on_the_fly'
      }
    });
    await prisma.reportDownload.create({
      data: {
        reportId: reportRecord.id,
        downloadedBy: req.user.id
      }
    });

  } catch (error) {
    console.error('Report generation error:', error);
    if (!res.headersSent) {
      res.status(500).json({ error: 'Internal server error during report generation' });
    }
  }
});

export default router;
